# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20171205_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='full_name',
            field=models.CharField(max_length=40, verbose_name='full_name'),
        ),
    ]
