# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-11-02 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20191102_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
